### ISSUE TITLE
Tipo: C / Cidade: Goiânia - GO - BR

### ISSUE THREAD

**Issue by guilhermemaranhao** [elastic/Elastic-Recognition-Program#127]
Nome: Guilherme Melo e Maranhão
Título: Searching for needle in haystack
URL: https://www.elastic.co/pt/blog/searching-for-needle-in-haystack
Data: 27/03/2017

**Comment by priscillaparodi** [comment]
Olá @guilhermemaranhao, a data da submissão é anterior ao prazo permitido. Por esse motivo não será considerada. Veja aqui as datas: https://elastic.github.io/Elastic-Recognition-Program/datas-prazos

Data de criação do conteúdo:
Desde 01/05/2018.
Até 31/10/2019.

ABS
